/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ChessGame.gui;

import ChessGame.model.ChessBoard;
import java.awt.Component;
import java.awt.GridLayout;

/**
 *
 * @author Rich
 */
public class ChessBoardUI extends javax.swing.JFrame {
    
    private ChessBoard board;
    private SquareGrid csSquareGrid;
    
    /**
     * Creates new form ChessBoardUI
     */
    public ChessBoardUI(ChessBoard board) {
        
        this.board = board;
        
        initComponents();
        createChessBoardGrid();
                
        csSquareGrid = new SquareGrid(board, 8, 8);
        csSquare.add(csSquareGrid);
        
        update();
        
    }
    
    private void update()
    {
        
        for ( Component component : csSquare.getComponents() )
        {
            SquareGrid gsp = (SquareGrid) component;
            gsp.update();
        }
        
        csSquareGrid.update();
    }
    
    private void createChessBoardGrid()
    {
        
        csSquare.removeAll();
        csSquare.setLayout(new GridLayout(8, 8));
        
        for ( int row = 0; row < 7; row++ )
        {
            for ( int col = 0; col < 9; col++ )
            {
                SquareGrid panel = new SquareGrid(board, row, col);
                csSquare.add(panel);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        csSquare = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        csSquare.setPreferredSize(new java.awt.Dimension(500, 400));
        csSquare.setLayout(new java.awt.BorderLayout());
        getContentPane().add(csSquare, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel csSquare;
    // End of variables declaration//GEN-END:variables
}
