/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ChessGame.gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Laz Bratton
 */
public class HighScoreTable extends javax.swing.JPanel {

    TableModel dataModel;
    JTable highScoreTable;
    /**
     * Creates new form HighScoreFrame
     */
    public HighScoreTable() {
        
        initComponents();
        dataModel = new AbstractTableModel() {
            public int getColumnCount() {return 10; }
            public int getRowCount() {return 10;}
            public Object getValueAt(int row, int col) {return new Integer(row*col);}
        
        };
        highScoreTable = new JTable(dataModel);
        JScrollPane scrollpane = new JScrollPane(highScoreTable);
        fillTable();
    }
    
    public void fillTable() {
        try {
        Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/ChessGame");
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT * FROM PLAYER");
        String n = "";
        int e = 0;
        DefaultTableModel model = (DefaultTableModel) highScoreTable.getModel();
        while(rs.next()) {
            n = rs.getString("NAME");
            e = rs.getInt("SCORE");
            model.insertRow(highScoreTable.getRowCount(), new Object[] {n,e});
        }
        }
        catch (SQLException e) {
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
