/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ChessGame.gui;

import ChessGame.model.ChessBoard;
import ChessGame.model.Chess;
import ChessGame.model.Position;
import ChessGame.model.Square;
import java.awt.Color;

/**
 *
 * @author Rich
 */
public final class SquareGrid extends javax.swing.JPanel {
    
    private ChessBoard board;
    private Chess chess;
    private Square square;
    private Position pos;
    private int row;
    private int column;

    /**
     * Creates new form SquareGrid
     */
    public SquareGrid(Chess chess, int row, int column) {
        
        this.chess = chess;
        this.row = row;
        this.column = column;
        initComponents();
        
        update();
    }
    
    public void update()
    {
        Square newSquare = chess.getSquare(row, column);
        //csLabel.setText("P");
        csLabel.setText(newSquare.getPieceStringRepresentation());
       
        //csPanel.setBackground(new java.awt.Color(255, 255, 255));
        
        for (int i = 0; i < 64; i++) {

        int row = (i / 8) % 2;
        if (row == 0)
            csPanel.setBackground( i % 2 == 0 ? Color.white : Color.black );
        else
            csPanel.setBackground( i % 2 == 0 ? Color.black : Color.white );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        csPanel = new javax.swing.JPanel();
        csLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        csPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                csPanelMouseReleased(evt);
            }
        });
        csPanel.setLayout(new java.awt.BorderLayout());

        csLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        csLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        csLabel.setText("csLabel");
        csLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        csPanel.add(csLabel, java.awt.BorderLayout.CENTER);

        add(csPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void csPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csPanelMouseReleased
        csLabel.setText("?");
    }//GEN-LAST:event_csPanelMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel csLabel;
    private javax.swing.JPanel csPanel;
    // End of variables declaration//GEN-END:variables
}
