/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ChessGame.gui;

import ChessGame.model.ChessBoard;
import ChessGame.model.Position;
import ChessGame.model.Square;

/**
 *
 * @author Rich
 */
public final class SquareGrid extends javax.swing.JPanel {
    
    private ChessBoard board;
    private Square square;
    private Position pos;
    private int row;
    private int column;

    /**
     * Creates new form SquareGrid
     */
    public SquareGrid(ChessBoard board, int row, int column) {
        
        this.board = board;
        this.row = row;
        this.column = column;
        initComponents();
        update();
    }
    
    public void update()
    {
        square = board.getSquare(pos);
        csLabel.setText(square.getPieceStringRepresentation());
        csPanel.setBackground(new java.awt.Color(240, 240, 240));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        csPanel = new javax.swing.JPanel();
        csLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        csPanel.setLayout(new java.awt.BorderLayout());

        csLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        csLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        csLabel.setText("csLabel");
        csPanel.add(csLabel, java.awt.BorderLayout.CENTER);

        add(csPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel csLabel;
    private javax.swing.JPanel csPanel;
    // End of variables declaration//GEN-END:variables
}
