/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ChessGame.gui;

import java.awt.Color;
import java.awt.Rectangle;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 *
 * @author Laz Bratton
 */
public class TextPane extends javax.swing.JPanel {
    
    private List<String> menuItems;
    private String selectMenuItem;
    private String focusedItem;
    
    //private MenuItemPainter painter;
    private Map<String, Rectangle> menuBounds;
    
    /**
     * Creates new form TextPane
     */
    public TextPane() {
        setBackground(Color.BLACK);
        menuItems = new ArrayList<>(25);
        menuItems.add("Start Game");
        menuItems.add("Instructions");
        menuItems.add("Exit");
        selectMenuItem = menuItems.get(0);
        
        MouseAdapter ma = new MouseAdapter() {
            
            @Override
            public void mouseClicked(MouseEvent e) {
                String newItem = null;
                for (String text: menuItems) {
                    Rectangle bounds = menuBounds.get(text);
                    if(bounds.contains(e.getPoint())) {
                        newItem = text;
                        break;
                    }
                }
                if(newItem != null && !newItem.equals(selectMenuItem)) {
                    selectMenuItem = newItem;
                    repaint();
                }
            }
            @Override
            public void mouseMoved(MouseEvent e) {
                focusedItem = null;
                for (String text : menuItems) {
                    Rectangle bounds = menuBounds.get(text);
                    if(bounds.contains(e.getPoint())) {
                        focusedItem = text;
                        repaint();
                        break;
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
